// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: api/goods/v1/goods.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttrValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AttrId        int64                  `protobuf:"varint,2,opt,name=attrId,proto3" json:"attrId,omitempty"`
	GroupId       int64                  `protobuf:"varint,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttrValueRequest) Reset() {
	*x = AttrValueRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttrValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrValueRequest) ProtoMessage() {}

func (x *AttrValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrValueRequest.ProtoReflect.Descriptor instead.
func (*AttrValueRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{0}
}

func (x *AttrValueRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttrValueRequest) GetAttrId() int64 {
	if x != nil {
		return x.AttrId
	}
	return 0
}

func (x *AttrValueRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *AttrValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AttrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId        int64                  `protobuf:"varint,2,opt,name=typeId,proto3" json:"typeId,omitempty"`
	GroupId       int64                  `protobuf:"varint,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Status        bool                   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Sort          int32                  `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	AttrValue     []*AttrValueRequest    `protobuf:"bytes,8,rep,name=attrValue,proto3" json:"attrValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttrRequest) Reset() {
	*x = AttrRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrRequest) ProtoMessage() {}

func (x *AttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrRequest.ProtoReflect.Descriptor instead.
func (*AttrRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{1}
}

func (x *AttrRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttrRequest) GetTypeId() int64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *AttrRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *AttrRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AttrRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *AttrRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *AttrRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *AttrRequest) GetAttrValue() []*AttrValueRequest {
	if x != nil {
		return x.AttrValue
	}
	return nil
}

type AttrValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AttrId        int64                  `protobuf:"varint,2,opt,name=attrId,proto3" json:"attrId,omitempty"`
	GroupId       int64                  `protobuf:"varint,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttrValueResponse) Reset() {
	*x = AttrValueResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttrValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrValueResponse) ProtoMessage() {}

func (x *AttrValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrValueResponse.ProtoReflect.Descriptor instead.
func (*AttrValueResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{2}
}

func (x *AttrValueResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttrValueResponse) GetAttrId() int64 {
	if x != nil {
		return x.AttrId
	}
	return 0
}

func (x *AttrValueResponse) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *AttrValueResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AttrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId        int64                  `protobuf:"varint,2,opt,name=typeId,proto3" json:"typeId,omitempty"`
	GroupId       int64                  `protobuf:"varint,3,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Status        bool                   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Sort          int32                  `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	AttrValue     []*AttrValueResponse   `protobuf:"bytes,8,rep,name=attrValue,proto3" json:"attrValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttrResponse) Reset() {
	*x = AttrResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrResponse) ProtoMessage() {}

func (x *AttrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrResponse.ProtoReflect.Descriptor instead.
func (*AttrResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{3}
}

func (x *AttrResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttrResponse) GetTypeId() int64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *AttrResponse) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *AttrResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AttrResponse) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *AttrResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *AttrResponse) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *AttrResponse) GetAttrValue() []*AttrValueResponse {
	if x != nil {
		return x.AttrValue
	}
	return nil
}

type AttrGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId        int64                  `protobuf:"varint,2,opt,name=typeId,proto3" json:"typeId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Status        bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Sort          int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttrGroupRequest) Reset() {
	*x = AttrGroupRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttrGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrGroupRequest) ProtoMessage() {}

func (x *AttrGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrGroupRequest.ProtoReflect.Descriptor instead.
func (*AttrGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{4}
}

func (x *AttrGroupRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttrGroupRequest) GetTypeId() int64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *AttrGroupRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AttrGroupRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *AttrGroupRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *AttrGroupRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type AttrGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId        int64                  `protobuf:"varint,2,opt,name=typeId,proto3" json:"typeId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	Status        bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Sort          int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttrGroupResponse) Reset() {
	*x = AttrGroupResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttrGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrGroupResponse) ProtoMessage() {}

func (x *AttrGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrGroupResponse.ProtoReflect.Descriptor instead.
func (*AttrGroupResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{5}
}

func (x *AttrGroupResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AttrGroupResponse) GetTypeId() int64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *AttrGroupResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AttrGroupResponse) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *AttrGroupResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *AttrGroupResponse) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type SpecificationValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AttrId        int64                  `protobuf:"varint,2,opt,name=attrId,proto3" json:"attrId,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecificationValue) Reset() {
	*x = SpecificationValue{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecificationValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecificationValue) ProtoMessage() {}

func (x *SpecificationValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecificationValue.ProtoReflect.Descriptor instead.
func (*SpecificationValue) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{6}
}

func (x *SpecificationValue) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpecificationValue) GetAttrId() int64 {
	if x != nil {
		return x.AttrId
	}
	return 0
}

func (x *SpecificationValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SpecificationValue) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type SpecificationValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AttrId        int64                  `protobuf:"varint,2,opt,name=attrId,proto3" json:"attrId,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Sort          int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecificationValueResponse) Reset() {
	*x = SpecificationValueResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecificationValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecificationValueResponse) ProtoMessage() {}

func (x *SpecificationValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecificationValueResponse.ProtoReflect.Descriptor instead.
func (*SpecificationValueResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{7}
}

func (x *SpecificationValueResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpecificationValueResponse) GetAttrId() int64 {
	if x != nil {
		return x.AttrId
	}
	return 0
}

func (x *SpecificationValueResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SpecificationValueResponse) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type SpecificationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId             int64                  `protobuf:"varint,2,opt,name=typeId,proto3" json:"typeId,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Sort               int32                  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	Status             bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	IsSku              bool                   `protobuf:"varint,6,opt,name=isSku,proto3" json:"isSku,omitempty"`
	IsSelect           bool                   `protobuf:"varint,7,opt,name=isSelect,proto3" json:"isSelect,omitempty"`
	SpecificationValue []*SpecificationValue  `protobuf:"bytes,8,rep,name=specificationValue,proto3" json:"specificationValue,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SpecificationRequest) Reset() {
	*x = SpecificationRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecificationRequest) ProtoMessage() {}

func (x *SpecificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecificationRequest.ProtoReflect.Descriptor instead.
func (*SpecificationRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{8}
}

func (x *SpecificationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SpecificationRequest) GetTypeId() int64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *SpecificationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpecificationRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *SpecificationRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *SpecificationRequest) GetIsSku() bool {
	if x != nil {
		return x.IsSku
	}
	return false
}

func (x *SpecificationRequest) GetIsSelect() bool {
	if x != nil {
		return x.IsSelect
	}
	return false
}

func (x *SpecificationRequest) GetSpecificationValue() []*SpecificationValue {
	if x != nil {
		return x.SpecificationValue
	}
	return nil
}

type SpecificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecificationResponse) Reset() {
	*x = SpecificationResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecificationResponse) ProtoMessage() {}

func (x *SpecificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecificationResponse.ProtoReflect.Descriptor instead.
func (*SpecificationResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{9}
}

func (x *SpecificationResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GoodsTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeCode      string                 `protobuf:"bytes,3,opt,name=typeCode,proto3" json:"typeCode,omitempty"`
	NameAlias     string                 `protobuf:"bytes,4,opt,name=nameAlias,proto3" json:"nameAlias,omitempty"`
	IsVirtual     bool                   `protobuf:"varint,5,opt,name=isVirtual,proto3" json:"isVirtual,omitempty"`
	Desc          string                 `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	Sort          int32                  `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	BrandIds      string                 `protobuf:"bytes,8,opt,name=brandIds,proto3" json:"brandIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsTypeRequest) Reset() {
	*x = GoodsTypeRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsTypeRequest) ProtoMessage() {}

func (x *GoodsTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsTypeRequest.ProtoReflect.Descriptor instead.
func (*GoodsTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{10}
}

func (x *GoodsTypeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsTypeRequest) GetTypeCode() string {
	if x != nil {
		return x.TypeCode
	}
	return ""
}

func (x *GoodsTypeRequest) GetNameAlias() string {
	if x != nil {
		return x.NameAlias
	}
	return ""
}

func (x *GoodsTypeRequest) GetIsVirtual() bool {
	if x != nil {
		return x.IsVirtual
	}
	return false
}

func (x *GoodsTypeRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GoodsTypeRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *GoodsTypeRequest) GetBrandIds() string {
	if x != nil {
		return x.BrandIds
	}
	return ""
}

type GoodsTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsTypeResponse) Reset() {
	*x = GoodsTypeResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsTypeResponse) ProtoMessage() {}

func (x *GoodsTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsTypeResponse.ProtoReflect.Descriptor instead.
func (*GoodsTypeResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{11}
}

func (x *GoodsTypeResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateGoodsRequest struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	Id              int64                         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId      int32                         `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	BrandId         int32                         `protobuf:"varint,3,opt,name=brandId,proto3" json:"brandId,omitempty"`
	TypeId          int64                         `protobuf:"varint,4,opt,name=typeId,proto3" json:"typeId,omitempty"`
	Name            string                        `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	NameAlias       string                        `protobuf:"bytes,6,opt,name=nameAlias,proto3" json:"nameAlias,omitempty"`
	GoodsTags       string                        `protobuf:"bytes,7,opt,name=goodsTags,proto3" json:"goodsTags,omitempty"`
	GoodsSn         string                        `protobuf:"bytes,8,opt,name=goodsSn,proto3" json:"goodsSn,omitempty"`
	ShopPrice       int64                         `protobuf:"varint,9,opt,name=shopPrice,proto3" json:"shopPrice,omitempty"`
	MarketPrice     int64                         `protobuf:"varint,10,opt,name=marketPrice,proto3" json:"marketPrice,omitempty"`
	Inventory       int64                         `protobuf:"varint,11,opt,name=inventory,proto3" json:"inventory,omitempty"`
	GoodsBrief      string                        `protobuf:"bytes,12,opt,name=goodsBrief,proto3" json:"goodsBrief,omitempty"`
	GoodsFrontImage string                        `protobuf:"bytes,13,opt,name=goodsFrontImage,proto3" json:"goodsFrontImage,omitempty"`
	GoodsImages     []string                      `protobuf:"bytes,14,rep,name=goodsImages,proto3" json:"goodsImages,omitempty"`
	ShipFree        bool                          `protobuf:"varint,15,opt,name=shipFree,proto3" json:"shipFree,omitempty"`
	ShipId          int32                         `protobuf:"varint,16,opt,name=shipId,proto3" json:"shipId,omitempty"`
	IsNew           bool                          `protobuf:"varint,17,opt,name=isNew,proto3" json:"isNew,omitempty"`
	IsHot           bool                          `protobuf:"varint,18,opt,name=isHot,proto3" json:"isHot,omitempty"`
	OnSale          bool                          `protobuf:"varint,19,opt,name=onSale,proto3" json:"onSale,omitempty"`
	Sku             []*CreateGoodsRequestGoodsSku `protobuf:"bytes,20,rep,name=sku,proto3" json:"sku,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGoodsRequest) Reset() {
	*x = CreateGoodsRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsRequest) ProtoMessage() {}

func (x *CreateGoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsRequest.ProtoReflect.Descriptor instead.
func (*CreateGoodsRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{12}
}

func (x *CreateGoodsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateGoodsRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateGoodsRequest) GetBrandId() int32 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *CreateGoodsRequest) GetTypeId() int64 {
	if x != nil {
		return x.TypeId
	}
	return 0
}

func (x *CreateGoodsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGoodsRequest) GetNameAlias() string {
	if x != nil {
		return x.NameAlias
	}
	return ""
}

func (x *CreateGoodsRequest) GetGoodsTags() string {
	if x != nil {
		return x.GoodsTags
	}
	return ""
}

func (x *CreateGoodsRequest) GetGoodsSn() string {
	if x != nil {
		return x.GoodsSn
	}
	return ""
}

func (x *CreateGoodsRequest) GetShopPrice() int64 {
	if x != nil {
		return x.ShopPrice
	}
	return 0
}

func (x *CreateGoodsRequest) GetMarketPrice() int64 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *CreateGoodsRequest) GetInventory() int64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *CreateGoodsRequest) GetGoodsBrief() string {
	if x != nil {
		return x.GoodsBrief
	}
	return ""
}

func (x *CreateGoodsRequest) GetGoodsFrontImage() string {
	if x != nil {
		return x.GoodsFrontImage
	}
	return ""
}

func (x *CreateGoodsRequest) GetGoodsImages() []string {
	if x != nil {
		return x.GoodsImages
	}
	return nil
}

func (x *CreateGoodsRequest) GetShipFree() bool {
	if x != nil {
		return x.ShipFree
	}
	return false
}

func (x *CreateGoodsRequest) GetShipId() int32 {
	if x != nil {
		return x.ShipId
	}
	return 0
}

func (x *CreateGoodsRequest) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *CreateGoodsRequest) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *CreateGoodsRequest) GetOnSale() bool {
	if x != nil {
		return x.OnSale
	}
	return false
}

func (x *CreateGoodsRequest) GetSku() []*CreateGoodsRequestGoodsSku {
	if x != nil {
		return x.Sku
	}
	return nil
}

type CreateGoodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGoodsResponse) Reset() {
	*x = CreateGoodsResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsResponse) ProtoMessage() {}

func (x *CreateGoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsResponse.ProtoReflect.Descriptor instead.
func (*CreateGoodsResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{13}
}

func (x *CreateGoodsResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GoodsInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	BrandId       int32                  `protobuf:"varint,3,opt,name=brandId,proto3" json:"brandId,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	GoodsSn       string                 `protobuf:"bytes,5,opt,name=goodsSn,proto3" json:"goodsSn,omitempty"`
	ClickNum      int64                  `protobuf:"varint,6,opt,name=clickNum,proto3" json:"clickNum,omitempty"`
	SoldNum       int64                  `protobuf:"varint,7,opt,name=soldNum,proto3" json:"soldNum,omitempty"`
	FavNum        int64                  `protobuf:"varint,8,opt,name=favNum,proto3" json:"favNum,omitempty"`
	MarketPrice   int64                  `protobuf:"varint,9,opt,name=marketPrice,proto3" json:"marketPrice,omitempty"`
	GoodsBrief    string                 `protobuf:"bytes,10,opt,name=goodsBrief,proto3" json:"goodsBrief,omitempty"`
	GoodsDesc     string                 `protobuf:"bytes,11,opt,name=goodsDesc,proto3" json:"goodsDesc,omitempty"`
	ShipFree      bool                   `protobuf:"varint,12,opt,name=shipFree,proto3" json:"shipFree,omitempty"`
	Images        string                 `protobuf:"bytes,13,opt,name=images,proto3" json:"images,omitempty"`
	GoodsImages   []string               `protobuf:"bytes,14,rep,name=goodsImages,proto3" json:"goodsImages,omitempty"`
	IsNew         bool                   `protobuf:"varint,15,opt,name=isNew,proto3" json:"isNew,omitempty"`
	IsHot         bool                   `protobuf:"varint,16,opt,name=isHot,proto3" json:"isHot,omitempty"`
	OnSale        bool                   `protobuf:"varint,17,opt,name=onSale,proto3" json:"onSale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInfoResponse) Reset() {
	*x = GoodsInfoResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoResponse) ProtoMessage() {}

func (x *GoodsInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoResponse.ProtoReflect.Descriptor instead.
func (*GoodsInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{14}
}

func (x *GoodsInfoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsInfoResponse) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GoodsInfoResponse) GetBrandId() int32 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *GoodsInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsInfoResponse) GetGoodsSn() string {
	if x != nil {
		return x.GoodsSn
	}
	return ""
}

func (x *GoodsInfoResponse) GetClickNum() int64 {
	if x != nil {
		return x.ClickNum
	}
	return 0
}

func (x *GoodsInfoResponse) GetSoldNum() int64 {
	if x != nil {
		return x.SoldNum
	}
	return 0
}

func (x *GoodsInfoResponse) GetFavNum() int64 {
	if x != nil {
		return x.FavNum
	}
	return 0
}

func (x *GoodsInfoResponse) GetMarketPrice() int64 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *GoodsInfoResponse) GetGoodsBrief() string {
	if x != nil {
		return x.GoodsBrief
	}
	return ""
}

func (x *GoodsInfoResponse) GetGoodsDesc() string {
	if x != nil {
		return x.GoodsDesc
	}
	return ""
}

func (x *GoodsInfoResponse) GetShipFree() bool {
	if x != nil {
		return x.ShipFree
	}
	return false
}

func (x *GoodsInfoResponse) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *GoodsInfoResponse) GetGoodsImages() []string {
	if x != nil {
		return x.GoodsImages
	}
	return nil
}

func (x *GoodsInfoResponse) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *GoodsInfoResponse) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *GoodsInfoResponse) GetOnSale() bool {
	if x != nil {
		return x.OnSale
	}
	return false
}

type GoodsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*GoodsInfoResponse   `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsListResponse) Reset() {
	*x = GoodsListResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsListResponse) ProtoMessage() {}

func (x *GoodsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsListResponse.ProtoReflect.Descriptor instead.
func (*GoodsListResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{15}
}

func (x *GoodsListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GoodsListResponse) GetList() []*GoodsInfoResponse {
	if x != nil {
		return x.List
	}
	return nil
}

type GoodsFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      string                 `protobuf:"bytes,1,opt,name=keywords,proto3" json:"keywords,omitempty"`
	CategoryId    int32                  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	BrandId       int32                  `protobuf:"varint,3,opt,name=brandId,proto3" json:"brandId,omitempty"`
	MinPrice      int64                  `protobuf:"varint,4,opt,name=minPrice,proto3" json:"minPrice,omitempty"`
	MaxPrice      int64                  `protobuf:"varint,5,opt,name=maxPrice,proto3" json:"maxPrice,omitempty"`
	IsHot         bool                   `protobuf:"varint,6,opt,name=isHot,proto3" json:"isHot,omitempty"`
	IsNew         bool                   `protobuf:"varint,7,opt,name=isNew,proto3" json:"isNew,omitempty"`
	IsTab         bool                   `protobuf:"varint,8,opt,name=isTab,proto3" json:"isTab,omitempty"`
	ClickNum      int64                  `protobuf:"varint,9,opt,name=clickNum,proto3" json:"clickNum,omitempty"`
	SoldNum       int64                  `protobuf:"varint,10,opt,name=soldNum,proto3" json:"soldNum,omitempty"`
	FavNum        int64                  `protobuf:"varint,11,opt,name=favNum,proto3" json:"favNum,omitempty"`
	Pages         int64                  `protobuf:"varint,12,opt,name=pages,proto3" json:"pages,omitempty"`
	PagePerNums   int64                  `protobuf:"varint,13,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"`
	Id            int64                  `protobuf:"varint,14,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsFilterRequest) Reset() {
	*x = GoodsFilterRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsFilterRequest) ProtoMessage() {}

func (x *GoodsFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsFilterRequest.ProtoReflect.Descriptor instead.
func (*GoodsFilterRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{16}
}

func (x *GoodsFilterRequest) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *GoodsFilterRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GoodsFilterRequest) GetBrandId() int32 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

func (x *GoodsFilterRequest) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *GoodsFilterRequest) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *GoodsFilterRequest) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *GoodsFilterRequest) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *GoodsFilterRequest) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

func (x *GoodsFilterRequest) GetClickNum() int64 {
	if x != nil {
		return x.ClickNum
	}
	return 0
}

func (x *GoodsFilterRequest) GetSoldNum() int64 {
	if x != nil {
		return x.SoldNum
	}
	return 0
}

func (x *GoodsFilterRequest) GetFavNum() int64 {
	if x != nil {
		return x.FavNum
	}
	return 0
}

func (x *GoodsFilterRequest) GetPages() int64 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *GoodsFilterRequest) GetPagePerNums() int64 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

func (x *GoodsFilterRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 商品分类
type CategoryInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentCategory int32                  `protobuf:"varint,3,opt,name=parentCategory,proto3" json:"parentCategory,omitempty"`
	Level          int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	IsTab          bool                   `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`
	Sort           int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CategoryInfoResponse) Reset() {
	*x = CategoryInfoResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfoResponse) ProtoMessage() {}

func (x *CategoryInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfoResponse.ProtoReflect.Descriptor instead.
func (*CategoryInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{17}
}

func (x *CategoryInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfoResponse) GetParentCategory() int32 {
	if x != nil {
		return x.ParentCategory
	}
	return 0
}

func (x *CategoryInfoResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CategoryInfoResponse) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

func (x *CategoryInfoResponse) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type CategoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonData      string                 `protobuf:"bytes,1,opt,name=jsonData,proto3" json:"jsonData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListResponse) Reset() {
	*x = CategoryListResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResponse) ProtoMessage() {}

func (x *CategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResponse.ProtoReflect.Descriptor instead.
func (*CategoryListResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{18}
}

func (x *CategoryListResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

type CategoryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListRequest) Reset() {
	*x = CategoryListRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListRequest) ProtoMessage() {}

func (x *CategoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListRequest.ProtoReflect.Descriptor instead.
func (*CategoryListRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{19}
}

func (x *CategoryListRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryListRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type SubCategoryListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Info          *CategoryInfoResponse   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	SubCategory   []*CategoryInfoResponse `protobuf:"bytes,2,rep,name=subCategory,proto3" json:"subCategory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCategoryListResponse) Reset() {
	*x = SubCategoryListResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCategoryListResponse) ProtoMessage() {}

func (x *SubCategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCategoryListResponse.ProtoReflect.Descriptor instead.
func (*SubCategoryListResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{20}
}

func (x *SubCategoryListResponse) GetInfo() *CategoryInfoResponse {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SubCategoryListResponse) GetSubCategory() []*CategoryInfoResponse {
	if x != nil {
		return x.SubCategory
	}
	return nil
}

type CategoryInfoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentCategory int32                  `protobuf:"varint,3,opt,name=parentCategory,proto3" json:"parentCategory,omitempty"`
	Level          int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	IsTab          bool                   `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`
	Sort           int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CategoryInfoRequest) Reset() {
	*x = CategoryInfoRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfoRequest) ProtoMessage() {}

func (x *CategoryInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfoRequest.ProtoReflect.Descriptor instead.
func (*CategoryInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{21}
}

func (x *CategoryInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfoRequest) GetParentCategory() int32 {
	if x != nil {
		return x.ParentCategory
	}
	return 0
}

func (x *CategoryInfoRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CategoryInfoRequest) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

func (x *CategoryInfoRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type BatchCategoryInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []int32                `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	GoodsNums     int32                  `protobuf:"varint,2,opt,name=goodsNums,proto3" json:"goodsNums,omitempty"`
	BrandNums     int32                  `protobuf:"varint,3,opt,name=brandNums,proto3" json:"brandNums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCategoryInfoRequest) Reset() {
	*x = BatchCategoryInfoRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCategoryInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCategoryInfoRequest) ProtoMessage() {}

func (x *BatchCategoryInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCategoryInfoRequest.ProtoReflect.Descriptor instead.
func (*BatchCategoryInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{22}
}

func (x *BatchCategoryInfoRequest) GetId() []int32 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BatchCategoryInfoRequest) GetGoodsNums() int32 {
	if x != nil {
		return x.GoodsNums
	}
	return 0
}

func (x *BatchCategoryInfoRequest) GetBrandNums() int32 {
	if x != nil {
		return x.BrandNums
	}
	return 0
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteCategoryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BrandListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         int32                  `protobuf:"varint,1,opt,name=pages,proto3" json:"pages,omitempty"`
	PagePerNums   int32                  `protobuf:"varint,2,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandListRequest) Reset() {
	*x = BrandListRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandListRequest) ProtoMessage() {}

func (x *BrandListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandListRequest.ProtoReflect.Descriptor instead.
func (*BrandListRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{24}
}

func (x *BrandListRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *BrandListRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

type BrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Logo          string                 `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	IsTab         bool                   `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`
	Sort          int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandRequest) Reset() {
	*x = BrandRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandRequest) ProtoMessage() {}

func (x *BrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandRequest.ProtoReflect.Descriptor instead.
func (*BrandRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{25}
}

func (x *BrandRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BrandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrandRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *BrandRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *BrandRequest) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

func (x *BrandRequest) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type BrandInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Logo          string                 `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"`
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	IsTab         bool                   `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`
	Sort          int32                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandInfoResponse) Reset() {
	*x = BrandInfoResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandInfoResponse) ProtoMessage() {}

func (x *BrandInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandInfoResponse.ProtoReflect.Descriptor instead.
func (*BrandInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{26}
}

func (x *BrandInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BrandInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrandInfoResponse) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *BrandInfoResponse) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *BrandInfoResponse) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

func (x *BrandInfoResponse) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

type BrandListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data          []*BrandInfoResponse   `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandListResponse) Reset() {
	*x = BrandListResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandListResponse) ProtoMessage() {}

func (x *BrandListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandListResponse.ProtoReflect.Descriptor instead.
func (*BrandListResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{27}
}

func (x *BrandListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BrandListResponse) GetData() []*BrandInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type SkuListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []int64                `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkuListRequest) Reset() {
	*x = SkuListRequest{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkuListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuListRequest) ProtoMessage() {}

func (x *SkuListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuListRequest.ProtoReflect.Descriptor instead.
func (*SkuListRequest) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{28}
}

func (x *SkuListRequest) GetId() []int64 {
	if x != nil {
		return x.Id
	}
	return nil
}

type SkuListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkuListResponse) Reset() {
	*x = SkuListResponse{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkuListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkuListResponse) ProtoMessage() {}

func (x *SkuListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkuListResponse.ProtoReflect.Descriptor instead.
func (*SkuListResponse) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{29}
}

// 根据商品类型 选择商品规格信息并选择
// 商品 sku 属性值 里面有规格的ID和属性的ID，分别是几组信息
type CreateGoodsRequestGoodsSku struct {
	state             protoimpl.MessageState                     `protogen:"open.v1"`
	Id                int64                                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GoodsId           int64                                      `protobuf:"varint,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	SkuName           string                                     `protobuf:"bytes,3,opt,name=skuName,proto3" json:"skuName,omitempty"`
	Code              string                                     `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	BarCode           string                                     `protobuf:"bytes,5,opt,name=barCode,proto3" json:"barCode,omitempty"`
	Price             int64                                      `protobuf:"varint,6,opt,name=price,proto3" json:"price,omitempty"`
	PromotionPrice    int64                                      `protobuf:"varint,7,opt,name=promotionPrice,proto3" json:"promotionPrice,omitempty"`
	Points            int64                                      `protobuf:"varint,8,opt,name=points,proto3" json:"points,omitempty"`
	Image             string                                     `protobuf:"bytes,9,opt,name=image,proto3" json:"image,omitempty"`
	Sort              int32                                      `protobuf:"varint,10,opt,name=sort,proto3" json:"sort,omitempty"`
	Inventory         int64                                      `protobuf:"varint,11,opt,name=inventory,proto3" json:"inventory,omitempty"` // sku 库存
	SpecificationInfo []*CreateGoodsRequestGoodsSkuSpecification `protobuf:"bytes,12,rep,name=specificationInfo,proto3" json:"specificationInfo,omitempty"`
	GroupAttrInfo     []*CreateGoodsRequestGoodsSkuGroupAttr     `protobuf:"bytes,13,rep,name=groupAttrInfo,proto3" json:"groupAttrInfo,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateGoodsRequestGoodsSku) Reset() {
	*x = CreateGoodsRequestGoodsSku{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoodsRequestGoodsSku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsRequestGoodsSku) ProtoMessage() {}

func (x *CreateGoodsRequestGoodsSku) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsRequestGoodsSku.ProtoReflect.Descriptor instead.
func (*CreateGoodsRequestGoodsSku) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{12, 0}
}

func (x *CreateGoodsRequestGoodsSku) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateGoodsRequestGoodsSku) GetGoodsId() int64 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *CreateGoodsRequestGoodsSku) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *CreateGoodsRequestGoodsSku) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateGoodsRequestGoodsSku) GetBarCode() string {
	if x != nil {
		return x.BarCode
	}
	return ""
}

func (x *CreateGoodsRequestGoodsSku) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateGoodsRequestGoodsSku) GetPromotionPrice() int64 {
	if x != nil {
		return x.PromotionPrice
	}
	return 0
}

func (x *CreateGoodsRequestGoodsSku) GetPoints() int64 {
	if x != nil {
		return x.Points
	}
	return 0
}

func (x *CreateGoodsRequestGoodsSku) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateGoodsRequestGoodsSku) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *CreateGoodsRequestGoodsSku) GetInventory() int64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *CreateGoodsRequestGoodsSku) GetSpecificationInfo() []*CreateGoodsRequestGoodsSkuSpecification {
	if x != nil {
		return x.SpecificationInfo
	}
	return nil
}

func (x *CreateGoodsRequestGoodsSku) GetGroupAttrInfo() []*CreateGoodsRequestGoodsSkuGroupAttr {
	if x != nil {
		return x.GroupAttrInfo
	}
	return nil
}

// 规格
type CreateGoodsRequestGoodsSkuSpecification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SId           int64                  `protobuf:"varint,1,opt,name=sId,proto3" json:"sId,omitempty"`
	VId           int64                  `protobuf:"varint,2,opt,name=vId,proto3" json:"vId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGoodsRequestGoodsSkuSpecification) Reset() {
	*x = CreateGoodsRequestGoodsSkuSpecification{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoodsRequestGoodsSkuSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsRequestGoodsSkuSpecification) ProtoMessage() {}

func (x *CreateGoodsRequestGoodsSkuSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsRequestGoodsSkuSpecification.ProtoReflect.Descriptor instead.
func (*CreateGoodsRequestGoodsSkuSpecification) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{12, 0, 0}
}

func (x *CreateGoodsRequestGoodsSkuSpecification) GetSId() int64 {
	if x != nil {
		return x.SId
	}
	return 0
}

func (x *CreateGoodsRequestGoodsSkuSpecification) GetVId() int64 {
	if x != nil {
		return x.VId
	}
	return 0
}

// 属性组
type CreateGoodsRequestGoodsSkuGroupAttr struct {
	state         protoimpl.MessageState                     `protogen:"open.v1"`
	GroupId       int64                                      `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	GroupName     string                                     `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName,omitempty"`
	AttrInfo      []*CreateGoodsRequestGoodsSkuGroupAttrAttr `protobuf:"bytes,3,rep,name=attrInfo,proto3" json:"attrInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGoodsRequestGoodsSkuGroupAttr) Reset() {
	*x = CreateGoodsRequestGoodsSkuGroupAttr{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoodsRequestGoodsSkuGroupAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsRequestGoodsSkuGroupAttr) ProtoMessage() {}

func (x *CreateGoodsRequestGoodsSkuGroupAttr) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsRequestGoodsSkuGroupAttr.ProtoReflect.Descriptor instead.
func (*CreateGoodsRequestGoodsSkuGroupAttr) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{12, 0, 1}
}

func (x *CreateGoodsRequestGoodsSkuGroupAttr) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGoodsRequestGoodsSkuGroupAttr) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateGoodsRequestGoodsSkuGroupAttr) GetAttrInfo() []*CreateGoodsRequestGoodsSkuGroupAttrAttr {
	if x != nil {
		return x.AttrInfo
	}
	return nil
}

type CreateGoodsRequestGoodsSkuGroupAttrAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttrId        int64                  `protobuf:"varint,1,opt,name=attrId,proto3" json:"attrId,omitempty"`
	AttrName      string                 `protobuf:"bytes,2,opt,name=attrName,proto3" json:"attrName,omitempty"`
	AttrValueId   int64                  `protobuf:"varint,3,opt,name=attrValueId,proto3" json:"attrValueId,omitempty"`
	AttrValueName string                 `protobuf:"bytes,4,opt,name=attrValueName,proto3" json:"attrValueName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGoodsRequestGoodsSkuGroupAttrAttr) Reset() {
	*x = CreateGoodsRequestGoodsSkuGroupAttrAttr{}
	mi := &file_api_goods_v1_goods_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoodsRequestGoodsSkuGroupAttrAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsRequestGoodsSkuGroupAttrAttr) ProtoMessage() {}

func (x *CreateGoodsRequestGoodsSkuGroupAttrAttr) ProtoReflect() protoreflect.Message {
	mi := &file_api_goods_v1_goods_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsRequestGoodsSkuGroupAttrAttr.ProtoReflect.Descriptor instead.
func (*CreateGoodsRequestGoodsSkuGroupAttrAttr) Descriptor() ([]byte, []int) {
	return file_api_goods_v1_goods_proto_rawDescGZIP(), []int{12, 0, 1, 0}
}

func (x *CreateGoodsRequestGoodsSkuGroupAttrAttr) GetAttrId() int64 {
	if x != nil {
		return x.AttrId
	}
	return 0
}

func (x *CreateGoodsRequestGoodsSkuGroupAttrAttr) GetAttrName() string {
	if x != nil {
		return x.AttrName
	}
	return ""
}

func (x *CreateGoodsRequestGoodsSkuGroupAttrAttr) GetAttrValueId() int64 {
	if x != nil {
		return x.AttrValueId
	}
	return 0
}

func (x *CreateGoodsRequestGoodsSkuGroupAttrAttr) GetAttrValueName() string {
	if x != nil {
		return x.AttrValueName
	}
	return ""
}

var File_api_goods_v1_goods_proto protoreflect.FileDescriptor

const file_api_goods_v1_goods_proto_rawDesc = "" +
	"\n" +
	"\x18api/goods/v1/goods.proto\x12\bgoods.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\"|\n" +
	"\x10AttrValueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06attrId\x18\x02 \x01(\x03R\x06attrId\x12!\n" +
	"\agroupId\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\agroupId\x12\x1d\n" +
	"\x05value\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\x05value\"\x83\x02\n" +
	"\vAttrRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\x06typeId\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\x06typeId\x12!\n" +
	"\agroupId\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\agroupId\x12\x1d\n" +
	"\x05title\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05title\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\x12\x16\n" +
	"\x06status\x18\x06 \x01(\bR\x06status\x12\x1b\n" +
	"\x04sort\x18\a \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x04sort\x128\n" +
	"\tattrValue\x18\b \x03(\v2\x1a.goods.v1.AttrValueRequestR\tattrValue\"k\n" +
	"\x11AttrValueResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06attrId\x18\x02 \x01(\x03R\x06attrId\x12\x18\n" +
	"\agroupId\x18\x03 \x01(\x03R\agroupId\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"\xe1\x01\n" +
	"\fAttrResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06typeId\x18\x02 \x01(\x03R\x06typeId\x12\x18\n" +
	"\agroupId\x18\x03 \x01(\x03R\agroupId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\x12\x16\n" +
	"\x06status\x18\x06 \x01(\bR\x06status\x12\x12\n" +
	"\x04sort\x18\a \x01(\x05R\x04sort\x129\n" +
	"\tattrValue\x18\b \x03(\v2\x1b.goods.v1.AttrValueResponseR\tattrValue\"\xab\x01\n" +
	"\x10AttrGroupRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\x06typeId\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\x06typeId\x12\x1d\n" +
	"\x05title\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\x05title\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\x12\x1b\n" +
	"\x04sort\x18\x06 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x04sort\"\x91\x01\n" +
	"\x11AttrGroupResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06typeId\x18\x02 \x01(\x03R\x06typeId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\"x\n" +
	"\x12SpecificationValue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06attrId\x18\x02 \x01(\x03R\x06attrId\x12\x1d\n" +
	"\x05value\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\x05value\x12\x1b\n" +
	"\x04sort\x18\x04 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x04sort\"n\n" +
	"\x1aSpecificationValueResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06attrId\x18\x02 \x01(\x03R\x06attrId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x12\n" +
	"\x04sort\x18\x04 \x01(\x05R\x04sort\"\x99\x02\n" +
	"\x14SpecificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\x06typeId\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\x06typeId\x12\x1b\n" +
	"\x04name\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x02R\x04name\x12\x1b\n" +
	"\x04sort\x18\x04 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x04sort\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\x12\x14\n" +
	"\x05isSku\x18\x06 \x01(\bR\x05isSku\x12\x1a\n" +
	"\bisSelect\x18\a \x01(\bR\bisSelect\x12L\n" +
	"\x12specificationValue\x18\b \x03(\v2\x1c.goods.v1.SpecificationValueR\x12specificationValue\"'\n" +
	"\x15SpecificationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xed\x01\n" +
	"\x10GoodsTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\x04name\x12#\n" +
	"\btypeCode\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x03R\btypeCode\x12\x1c\n" +
	"\tnameAlias\x18\x04 \x01(\tR\tnameAlias\x12\x1c\n" +
	"\tisVirtual\x18\x05 \x01(\bR\tisVirtual\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12\x12\n" +
	"\x04sort\x18\a \x01(\x05R\x04sort\x12#\n" +
	"\bbrandIds\x18\b \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bbrandIds\"#\n" +
	"\x11GoodsTypeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xf0\v\n" +
	"\x12CreateGoodsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12'\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\n" +
	"categoryId\x12!\n" +
	"\abrandId\x18\x03 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\abrandId\x12\x1f\n" +
	"\x06typeId\x18\x04 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\x06typeId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1c\n" +
	"\tnameAlias\x18\x06 \x01(\tR\tnameAlias\x12\x1c\n" +
	"\tgoodsTags\x18\a \x01(\tR\tgoodsTags\x12\x18\n" +
	"\agoodsSn\x18\b \x01(\tR\agoodsSn\x12\x1c\n" +
	"\tshopPrice\x18\t \x01(\x03R\tshopPrice\x12 \n" +
	"\vmarketPrice\x18\n" +
	" \x01(\x03R\vmarketPrice\x12\x1c\n" +
	"\tinventory\x18\v \x01(\x03R\tinventory\x12\x1e\n" +
	"\n" +
	"goodsBrief\x18\f \x01(\tR\n" +
	"goodsBrief\x12(\n" +
	"\x0fgoodsFrontImage\x18\r \x01(\tR\x0fgoodsFrontImage\x12 \n" +
	"\vgoodsImages\x18\x0e \x03(\tR\vgoodsImages\x12\x1a\n" +
	"\bshipFree\x18\x0f \x01(\bR\bshipFree\x12\x16\n" +
	"\x06shipId\x18\x10 \x01(\x05R\x06shipId\x12\x14\n" +
	"\x05isNew\x18\x11 \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isHot\x18\x12 \x01(\bR\x05isHot\x12\x16\n" +
	"\x06onSale\x18\x13 \x01(\bR\x06onSale\x127\n" +
	"\x03sku\x18\x14 \x03(\v2%.goods.v1.CreateGoodsRequest.goodsSkuR\x03sku\x1a\xf7\x06\n" +
	"\bgoodsSku\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\agoodsId\x18\x02 \x01(\x03R\agoodsId\x12!\n" +
	"\askuName\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\askuName\x12\x1b\n" +
	"\x04code\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04code\x12!\n" +
	"\abarCode\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\abarCode\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x03R\x05price\x12&\n" +
	"\x0epromotionPrice\x18\a \x01(\x03R\x0epromotionPrice\x12\x16\n" +
	"\x06points\x18\b \x01(\x03R\x06points\x12\x14\n" +
	"\x05image\x18\t \x01(\tR\x05image\x12\x12\n" +
	"\x04sort\x18\n" +
	" \x01(\x05R\x04sort\x12\x1c\n" +
	"\tinventory\x18\v \x01(\x03R\tinventory\x12a\n" +
	"\x11specificationInfo\x18\f \x03(\v23.goods.v1.CreateGoodsRequest.goodsSku.specificationR\x11specificationInfo\x12U\n" +
	"\rgroupAttrInfo\x18\r \x03(\v2/.goods.v1.CreateGoodsRequest.goodsSku.groupAttrR\rgroupAttrInfo\x1aE\n" +
	"\rspecification\x12\x19\n" +
	"\x03sId\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\x03sId\x12\x19\n" +
	"\x03vId\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\x03vId\x1a\xbe\x02\n" +
	"\tgroupAttr\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\x03R\agroupId\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12P\n" +
	"\battrInfo\x18\x03 \x03(\v24.goods.v1.CreateGoodsRequest.goodsSku.groupAttr.attrR\battrInfo\x1a\xa6\x01\n" +
	"\x04attr\x12\x1f\n" +
	"\x06attrId\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\x06attrId\x12#\n" +
	"\battrName\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\battrName\x12)\n" +
	"\vattrValueId\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02(\x01R\vattrValueId\x12-\n" +
	"\rattrValueName\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\rattrValueName\"%\n" +
	"\x13CreateGoodsResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\"\xd3\x03\n" +
	"\x11GoodsInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x18\n" +
	"\abrandId\x18\x03 \x01(\x05R\abrandId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\agoodsSn\x18\x05 \x01(\tR\agoodsSn\x12\x1a\n" +
	"\bclickNum\x18\x06 \x01(\x03R\bclickNum\x12\x18\n" +
	"\asoldNum\x18\a \x01(\x03R\asoldNum\x12\x16\n" +
	"\x06favNum\x18\b \x01(\x03R\x06favNum\x12 \n" +
	"\vmarketPrice\x18\t \x01(\x03R\vmarketPrice\x12\x1e\n" +
	"\n" +
	"goodsBrief\x18\n" +
	" \x01(\tR\n" +
	"goodsBrief\x12\x1c\n" +
	"\tgoodsDesc\x18\v \x01(\tR\tgoodsDesc\x12\x1a\n" +
	"\bshipFree\x18\f \x01(\bR\bshipFree\x12\x16\n" +
	"\x06images\x18\r \x01(\tR\x06images\x12 \n" +
	"\vgoodsImages\x18\x0e \x03(\tR\vgoodsImages\x12\x14\n" +
	"\x05isNew\x18\x0f \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isHot\x18\x10 \x01(\bR\x05isHot\x12\x16\n" +
	"\x06onSale\x18\x11 \x01(\bR\x06onSale\"Z\n" +
	"\x11GoodsListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12/\n" +
	"\x04list\x18\x02 \x03(\v2\x1b.goods.v1.GoodsInfoResponseR\x04list\"\xfa\x02\n" +
	"\x12GoodsFilterRequest\x12\x1a\n" +
	"\bkeywords\x18\x01 \x01(\tR\bkeywords\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x18\n" +
	"\abrandId\x18\x03 \x01(\x05R\abrandId\x12\x1a\n" +
	"\bminPrice\x18\x04 \x01(\x03R\bminPrice\x12\x1a\n" +
	"\bmaxPrice\x18\x05 \x01(\x03R\bmaxPrice\x12\x14\n" +
	"\x05isHot\x18\x06 \x01(\bR\x05isHot\x12\x14\n" +
	"\x05isNew\x18\a \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isTab\x18\b \x01(\bR\x05isTab\x12\x1a\n" +
	"\bclickNum\x18\t \x01(\x03R\bclickNum\x12\x18\n" +
	"\asoldNum\x18\n" +
	" \x01(\x03R\asoldNum\x12\x16\n" +
	"\x06favNum\x18\v \x01(\x03R\x06favNum\x12\x14\n" +
	"\x05pages\x18\f \x01(\x03R\x05pages\x12 \n" +
	"\vpagePerNums\x18\r \x01(\x03R\vpagePerNums\x12\x0e\n" +
	"\x02id\x18\x0e \x01(\x03R\x02id\"\xa2\x01\n" +
	"\x14CategoryInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0eparentCategory\x18\x03 \x01(\x05R\x0eparentCategory\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\"2\n" +
	"\x14CategoryListResponse\x12\x1a\n" +
	"\bjsonData\x18\x01 \x01(\tR\bjsonData\";\n" +
	"\x13CategoryListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"\x8f\x01\n" +
	"\x17SubCategoryListResponse\x122\n" +
	"\x04info\x18\x01 \x01(\v2\x1e.goods.v1.CategoryInfoResponseR\x04info\x12@\n" +
	"\vsubCategory\x18\x02 \x03(\v2\x1e.goods.v1.CategoryInfoResponseR\vsubCategory\"\xa1\x01\n" +
	"\x13CategoryInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0eparentCategory\x18\x03 \x01(\x05R\x0eparentCategory\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\"f\n" +
	"\x18BatchCategoryInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x05R\x02id\x12\x1c\n" +
	"\tgoodsNums\x18\x02 \x01(\x05R\tgoodsNums\x12\x1c\n" +
	"\tbrandNums\x18\x03 \x01(\x05R\tbrandNums\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"J\n" +
	"\x10BrandListRequest\x12\x14\n" +
	"\x05pages\x18\x01 \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\x02 \x01(\x05R\vpagePerNums\"\x84\x01\n" +
	"\fBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\tR\x04logo\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\"\x89\x01\n" +
	"\x11BrandInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\tR\x04logo\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x05R\x04sort\"Z\n" +
	"\x11BrandListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12/\n" +
	"\x04data\x18\x02 \x03(\v2\x1b.goods.v1.BrandInfoResponseR\x04data\" \n" +
	"\x0eSkuListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x03R\x02id\"\x11\n" +
	"\x0fSkuListResponse2\xe6\t\n" +
	"\x05Goods\x12L\n" +
	"\x12GetAllCategoryList\x12\x16.google.protobuf.Empty\x1a\x1e.goods.v1.CategoryListResponse\x12R\n" +
	"\x0eGetSubCategory\x12\x1d.goods.v1.CategoryListRequest\x1a!.goods.v1.SubCategoryListResponse\x12O\n" +
	"\x0eCreateCategory\x12\x1d.goods.v1.CategoryInfoRequest\x1a\x1e.goods.v1.CategoryInfoResponse\x12I\n" +
	"\x0eDeleteCategory\x12\x1f.goods.v1.DeleteCategoryRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\x0eUpdateCategory\x12\x1d.goods.v1.CategoryInfoRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\tBrandList\x12\x1a.goods.v1.BrandListRequest\x1a\x1b.goods.v1.BrandListResponse\x12B\n" +
	"\vCreateBrand\x12\x16.goods.v1.BrandRequest\x1a\x1b.goods.v1.BrandInfoResponse\x12=\n" +
	"\vDeleteBrand\x12\x16.goods.v1.BrandRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\vUpdateBrand\x12\x16.goods.v1.BrandRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0fCreateGoodsType\x12\x1a.goods.v1.GoodsTypeRequest\x1a\x1b.goods.v1.GoodsTypeResponse\x12[\n" +
	"\x18CreateGoodsSpecification\x12\x1e.goods.v1.SpecificationRequest\x1a\x1f.goods.v1.SpecificationResponse\x12J\n" +
	"\x0fCreateAttrGroup\x12\x1a.goods.v1.AttrGroupRequest\x1a\x1b.goods.v1.AttrGroupResponse\x12@\n" +
	"\x0fCreateAttrValue\x12\x15.goods.v1.AttrRequest\x1a\x16.goods.v1.AttrResponse\x12J\n" +
	"\vCreateGoods\x12\x1c.goods.v1.CreateGoodsRequest\x1a\x1d.goods.v1.CreateGoodsResponse\x12C\n" +
	"\vUpdateGoods\x12\x1c.goods.v1.CreateGoodsRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\tGoodsList\x12\x1c.goods.v1.GoodsFilterRequest\x1a\x1b.goods.v1.GoodsListResponse\x12>\n" +
	"\aSkuList\x12\x18.goods.v1.SkuListRequest\x1a\x19.goods.v1.SkuListResponseB\x17Z\x15goods/api/goods/v1;v1b\x06proto3"

var (
	file_api_goods_v1_goods_proto_rawDescOnce sync.Once
	file_api_goods_v1_goods_proto_rawDescData []byte
)

func file_api_goods_v1_goods_proto_rawDescGZIP() []byte {
	file_api_goods_v1_goods_proto_rawDescOnce.Do(func() {
		file_api_goods_v1_goods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_goods_v1_goods_proto_rawDesc), len(file_api_goods_v1_goods_proto_rawDesc)))
	})
	return file_api_goods_v1_goods_proto_rawDescData
}

var file_api_goods_v1_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_goods_v1_goods_proto_goTypes = []any{
	(*AttrValueRequest)(nil),                        // 0: goods.v1.AttrValueRequest
	(*AttrRequest)(nil),                             // 1: goods.v1.AttrRequest
	(*AttrValueResponse)(nil),                       // 2: goods.v1.AttrValueResponse
	(*AttrResponse)(nil),                            // 3: goods.v1.AttrResponse
	(*AttrGroupRequest)(nil),                        // 4: goods.v1.AttrGroupRequest
	(*AttrGroupResponse)(nil),                       // 5: goods.v1.AttrGroupResponse
	(*SpecificationValue)(nil),                      // 6: goods.v1.SpecificationValue
	(*SpecificationValueResponse)(nil),              // 7: goods.v1.SpecificationValueResponse
	(*SpecificationRequest)(nil),                    // 8: goods.v1.SpecificationRequest
	(*SpecificationResponse)(nil),                   // 9: goods.v1.SpecificationResponse
	(*GoodsTypeRequest)(nil),                        // 10: goods.v1.GoodsTypeRequest
	(*GoodsTypeResponse)(nil),                       // 11: goods.v1.GoodsTypeResponse
	(*CreateGoodsRequest)(nil),                      // 12: goods.v1.CreateGoodsRequest
	(*CreateGoodsResponse)(nil),                     // 13: goods.v1.CreateGoodsResponse
	(*GoodsInfoResponse)(nil),                       // 14: goods.v1.GoodsInfoResponse
	(*GoodsListResponse)(nil),                       // 15: goods.v1.GoodsListResponse
	(*GoodsFilterRequest)(nil),                      // 16: goods.v1.GoodsFilterRequest
	(*CategoryInfoResponse)(nil),                    // 17: goods.v1.CategoryInfoResponse
	(*CategoryListResponse)(nil),                    // 18: goods.v1.CategoryListResponse
	(*CategoryListRequest)(nil),                     // 19: goods.v1.CategoryListRequest
	(*SubCategoryListResponse)(nil),                 // 20: goods.v1.SubCategoryListResponse
	(*CategoryInfoRequest)(nil),                     // 21: goods.v1.CategoryInfoRequest
	(*BatchCategoryInfoRequest)(nil),                // 22: goods.v1.BatchCategoryInfoRequest
	(*DeleteCategoryRequest)(nil),                   // 23: goods.v1.DeleteCategoryRequest
	(*BrandListRequest)(nil),                        // 24: goods.v1.BrandListRequest
	(*BrandRequest)(nil),                            // 25: goods.v1.BrandRequest
	(*BrandInfoResponse)(nil),                       // 26: goods.v1.BrandInfoResponse
	(*BrandListResponse)(nil),                       // 27: goods.v1.BrandListResponse
	(*SkuListRequest)(nil),                          // 28: goods.v1.SkuListRequest
	(*SkuListResponse)(nil),                         // 29: goods.v1.SkuListResponse
	(*CreateGoodsRequestGoodsSku)(nil),              // 30: goods.v1.CreateGoodsRequest.goodsSku
	(*CreateGoodsRequestGoodsSkuSpecification)(nil), // 31: goods.v1.CreateGoodsRequest.goodsSku.specification
	(*CreateGoodsRequestGoodsSkuGroupAttr)(nil),     // 32: goods.v1.CreateGoodsRequest.goodsSku.groupAttr
	(*CreateGoodsRequestGoodsSkuGroupAttrAttr)(nil), // 33: goods.v1.CreateGoodsRequest.goodsSku.groupAttr.attr
	(*emptypb.Empty)(nil),                           // 34: google.protobuf.Empty
}
var file_api_goods_v1_goods_proto_depIdxs = []int32{
	0,  // 0: goods.v1.AttrRequest.attrValue:type_name -> goods.v1.AttrValueRequest
	2,  // 1: goods.v1.AttrResponse.attrValue:type_name -> goods.v1.AttrValueResponse
	6,  // 2: goods.v1.SpecificationRequest.specificationValue:type_name -> goods.v1.SpecificationValue
	30, // 3: goods.v1.CreateGoodsRequest.sku:type_name -> goods.v1.CreateGoodsRequest.goodsSku
	14, // 4: goods.v1.GoodsListResponse.list:type_name -> goods.v1.GoodsInfoResponse
	17, // 5: goods.v1.SubCategoryListResponse.info:type_name -> goods.v1.CategoryInfoResponse
	17, // 6: goods.v1.SubCategoryListResponse.subCategory:type_name -> goods.v1.CategoryInfoResponse
	26, // 7: goods.v1.BrandListResponse.data:type_name -> goods.v1.BrandInfoResponse
	31, // 8: goods.v1.CreateGoodsRequest.goodsSku.specificationInfo:type_name -> goods.v1.CreateGoodsRequest.goodsSku.specification
	32, // 9: goods.v1.CreateGoodsRequest.goodsSku.groupAttrInfo:type_name -> goods.v1.CreateGoodsRequest.goodsSku.groupAttr
	33, // 10: goods.v1.CreateGoodsRequest.goodsSku.groupAttr.attrInfo:type_name -> goods.v1.CreateGoodsRequest.goodsSku.groupAttr.attr
	34, // 11: goods.v1.Goods.GetAllCategoryList:input_type -> google.protobuf.Empty
	19, // 12: goods.v1.Goods.GetSubCategory:input_type -> goods.v1.CategoryListRequest
	21, // 13: goods.v1.Goods.CreateCategory:input_type -> goods.v1.CategoryInfoRequest
	23, // 14: goods.v1.Goods.DeleteCategory:input_type -> goods.v1.DeleteCategoryRequest
	21, // 15: goods.v1.Goods.UpdateCategory:input_type -> goods.v1.CategoryInfoRequest
	24, // 16: goods.v1.Goods.BrandList:input_type -> goods.v1.BrandListRequest
	25, // 17: goods.v1.Goods.CreateBrand:input_type -> goods.v1.BrandRequest
	25, // 18: goods.v1.Goods.DeleteBrand:input_type -> goods.v1.BrandRequest
	25, // 19: goods.v1.Goods.UpdateBrand:input_type -> goods.v1.BrandRequest
	10, // 20: goods.v1.Goods.CreateGoodsType:input_type -> goods.v1.GoodsTypeRequest
	8,  // 21: goods.v1.Goods.CreateGoodsSpecification:input_type -> goods.v1.SpecificationRequest
	4,  // 22: goods.v1.Goods.CreateAttrGroup:input_type -> goods.v1.AttrGroupRequest
	1,  // 23: goods.v1.Goods.CreateAttrValue:input_type -> goods.v1.AttrRequest
	12, // 24: goods.v1.Goods.CreateGoods:input_type -> goods.v1.CreateGoodsRequest
	12, // 25: goods.v1.Goods.UpdateGoods:input_type -> goods.v1.CreateGoodsRequest
	16, // 26: goods.v1.Goods.GoodsList:input_type -> goods.v1.GoodsFilterRequest
	28, // 27: goods.v1.Goods.SkuList:input_type -> goods.v1.SkuListRequest
	18, // 28: goods.v1.Goods.GetAllCategoryList:output_type -> goods.v1.CategoryListResponse
	20, // 29: goods.v1.Goods.GetSubCategory:output_type -> goods.v1.SubCategoryListResponse
	17, // 30: goods.v1.Goods.CreateCategory:output_type -> goods.v1.CategoryInfoResponse
	34, // 31: goods.v1.Goods.DeleteCategory:output_type -> google.protobuf.Empty
	34, // 32: goods.v1.Goods.UpdateCategory:output_type -> google.protobuf.Empty
	27, // 33: goods.v1.Goods.BrandList:output_type -> goods.v1.BrandListResponse
	26, // 34: goods.v1.Goods.CreateBrand:output_type -> goods.v1.BrandInfoResponse
	34, // 35: goods.v1.Goods.DeleteBrand:output_type -> google.protobuf.Empty
	34, // 36: goods.v1.Goods.UpdateBrand:output_type -> google.protobuf.Empty
	11, // 37: goods.v1.Goods.CreateGoodsType:output_type -> goods.v1.GoodsTypeResponse
	9,  // 38: goods.v1.Goods.CreateGoodsSpecification:output_type -> goods.v1.SpecificationResponse
	5,  // 39: goods.v1.Goods.CreateAttrGroup:output_type -> goods.v1.AttrGroupResponse
	3,  // 40: goods.v1.Goods.CreateAttrValue:output_type -> goods.v1.AttrResponse
	13, // 41: goods.v1.Goods.CreateGoods:output_type -> goods.v1.CreateGoodsResponse
	34, // 42: goods.v1.Goods.UpdateGoods:output_type -> google.protobuf.Empty
	15, // 43: goods.v1.Goods.GoodsList:output_type -> goods.v1.GoodsListResponse
	29, // 44: goods.v1.Goods.SkuList:output_type -> goods.v1.SkuListResponse
	28, // [28:45] is the sub-list for method output_type
	11, // [11:28] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_goods_v1_goods_proto_init() }
func file_api_goods_v1_goods_proto_init() {
	if File_api_goods_v1_goods_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_goods_v1_goods_proto_rawDesc), len(file_api_goods_v1_goods_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_goods_v1_goods_proto_goTypes,
		DependencyIndexes: file_api_goods_v1_goods_proto_depIdxs,
		MessageInfos:      file_api_goods_v1_goods_proto_msgTypes,
	}.Build()
	File_api_goods_v1_goods_proto = out.File
	file_api_goods_v1_goods_proto_goTypes = nil
	file_api_goods_v1_goods_proto_depIdxs = nil
}
