// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: shop/v1/user.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data returned by registration and login
type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile        string                 `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	ExpiredAt     int64                  `protobuf:"varint,6,opt,name=expiredAt,proto3" json:"expiredAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_shop_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_shop_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterReply) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterReply) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterReply) GetExpiredAt() int64 {
	if x != nil {
		return x.ExpiredAt
	}
	return 0
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_shop_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_shop_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Captcha       string                 `protobuf:"bytes,3,opt,name=captcha,proto3" json:"captcha,omitempty"`
	CaptchaId     string                 `protobuf:"bytes,4,opt,name=captchaId,proto3" json:"captchaId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_shop_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_shop_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetCaptcha() string {
	if x != nil {
		return x.Captcha
	}
	return ""
}

func (x *LoginReq) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

// user Detail returned
type UserDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile        string                 `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	NickName      string                 `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Birthday      int64                  `protobuf:"varint,4,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Gender        string                 `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Role          int32                  `protobuf:"varint,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailResponse) Reset() {
	*x = UserDetailResponse{}
	mi := &file_shop_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailResponse) ProtoMessage() {}

func (x *UserDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailResponse.ProtoReflect.Descriptor instead.
func (*UserDetailResponse) Descriptor() ([]byte, []int) {
	return file_shop_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserDetailResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserDetailResponse) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *UserDetailResponse) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserDetailResponse) GetBirthday() int64 {
	if x != nil {
		return x.Birthday
	}
	return 0
}

func (x *UserDetailResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UserDetailResponse) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type CaptchaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaptchaId     string                 `protobuf:"bytes,1,opt,name=captchaId,proto3" json:"captchaId,omitempty"`
	PicPath       string                 `protobuf:"bytes,2,opt,name=picPath,proto3" json:"picPath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptchaReply) Reset() {
	*x = CaptchaReply{}
	mi := &file_shop_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaReply) ProtoMessage() {}

func (x *CaptchaReply) ProtoReflect() protoreflect.Message {
	mi := &file_shop_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaReply.ProtoReflect.Descriptor instead.
func (*CaptchaReply) Descriptor() ([]byte, []int) {
	return file_shop_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *CaptchaReply) GetCaptchaId() string {
	if x != nil {
		return x.CaptchaId
	}
	return ""
}

func (x *CaptchaReply) GetPicPath() string {
	if x != nil {
		return x.PicPath
	}
	return ""
}

var File_shop_v1_user_proto protoreflect.FileDescriptor

const file_shop_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x12shop/v1/user.proto\x12\fshop.shop.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x17validate/validate.proto\"\x87\x01\n" +
	"\rRegisterReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06mobile\x18\x03 \x01(\tR\x06mobile\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\x12\x1c\n" +
	"\texpiredAt\x18\x06 \x01(\x03R\texpiredAt\"{\n" +
	"\vRegisterReq\x12 \n" +
	"\x06mobile\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x98\x01\vR\x06mobile\x12%\n" +
	"\busername\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x03\x18\x0fR\busername\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\bR\bpassword\"\x9d\x01\n" +
	"\bLoginReq\x12 \n" +
	"\x06mobile\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x98\x01\vR\x06mobile\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\bR\bpassword\x12#\n" +
	"\acaptcha\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x05\x18\x05R\acaptcha\x12%\n" +
	"\tcaptchaId\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tcaptchaId\"\xa0\x01\n" +
	"\x12UserDetailResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06mobile\x18\x02 \x01(\tR\x06mobile\x12\x1a\n" +
	"\bnickName\x18\x03 \x01(\tR\bnickName\x12\x1a\n" +
	"\bbirthday\x18\x04 \x01(\x03R\bbirthday\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\tR\x06gender\x12\x12\n" +
	"\x04role\x18\x06 \x01(\x05R\x04role\"F\n" +
	"\fCaptchaReply\x12\x1c\n" +
	"\tcaptchaId\x18\x01 \x01(\tR\tcaptchaId\x12\x18\n" +
	"\apicPath\x18\x02 \x01(\tR\apicPath2\xff\x02\n" +
	"\x04Shop\x12b\n" +
	"\bRegister\x12\x19.shop.shop.v1.RegisterReq\x1a\x1b.shop.shop.v1.RegisterReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/users/register\x12Y\n" +
	"\x05Login\x12\x16.shop.shop.v1.LoginReq\x1a\x1b.shop.shop.v1.RegisterReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/users/login\x12Y\n" +
	"\aCaptcha\x12\x16.google.protobuf.Empty\x1a\x1a.shop.shop.v1.CaptchaReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/users/captcha\x12]\n" +
	"\x06Detail\x12\x16.google.protobuf.Empty\x1a .shop.shop.v1.UserDetailResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/users/detailB\x15Z\x13shop/api/shop/v1;v1b\x06proto3"

var (
	file_shop_v1_user_proto_rawDescOnce sync.Once
	file_shop_v1_user_proto_rawDescData []byte
)

func file_shop_v1_user_proto_rawDescGZIP() []byte {
	file_shop_v1_user_proto_rawDescOnce.Do(func() {
		file_shop_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shop_v1_user_proto_rawDesc), len(file_shop_v1_user_proto_rawDesc)))
	})
	return file_shop_v1_user_proto_rawDescData
}

var file_shop_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shop_v1_user_proto_goTypes = []any{
	(*RegisterReply)(nil),      // 0: shop.shop.v1.RegisterReply
	(*RegisterReq)(nil),        // 1: shop.shop.v1.RegisterReq
	(*LoginReq)(nil),           // 2: shop.shop.v1.LoginReq
	(*UserDetailResponse)(nil), // 3: shop.shop.v1.UserDetailResponse
	(*CaptchaReply)(nil),       // 4: shop.shop.v1.CaptchaReply
	(*emptypb.Empty)(nil),      // 5: google.protobuf.Empty
}
var file_shop_v1_user_proto_depIdxs = []int32{
	1, // 0: shop.shop.v1.Shop.Register:input_type -> shop.shop.v1.RegisterReq
	2, // 1: shop.shop.v1.Shop.Login:input_type -> shop.shop.v1.LoginReq
	5, // 2: shop.shop.v1.Shop.Captcha:input_type -> google.protobuf.Empty
	5, // 3: shop.shop.v1.Shop.Detail:input_type -> google.protobuf.Empty
	0, // 4: shop.shop.v1.Shop.Register:output_type -> shop.shop.v1.RegisterReply
	0, // 5: shop.shop.v1.Shop.Login:output_type -> shop.shop.v1.RegisterReply
	4, // 6: shop.shop.v1.Shop.Captcha:output_type -> shop.shop.v1.CaptchaReply
	3, // 7: shop.shop.v1.Shop.Detail:output_type -> shop.shop.v1.UserDetailResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shop_v1_user_proto_init() }
func file_shop_v1_user_proto_init() {
	if File_shop_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shop_v1_user_proto_rawDesc), len(file_shop_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shop_v1_user_proto_goTypes,
		DependencyIndexes: file_shop_v1_user_proto_depIdxs,
		MessageInfos:      file_shop_v1_user_proto_msgTypes,
	}.Build()
	File_shop_v1_user_proto = out.File
	file_shop_v1_user_proto_goTypes = nil
	file_shop_v1_user_proto_depIdxs = nil
}
